### ISSUE TITLE
Segfault found by fuzzer

### ISSUE THREAD

**Issue by maxhawkins** [pion/sdp#13]
Unmarshaling this SDP produces a SEGFAULT

```
v=0
o=1 4 0 IN IP4 0
s=
t=0 0
a=
m=audio 6 UDP/TLS/RTP/AVP 197
c=IN IP4 63.245.221.198
a=candidate:0 1 UDP 2122187007 2620:101:80fc:224:8dd:cbf5:24c1:35db 52629 typ host
a=candidate:2 1 UDP 2122252543 2620:101:80fc:224:219d:9e56:e0e3:9503 52630 typ host
a=candidate:4 1 UDP 2122121471 10.252.25.57 53802 typ host
a=candidate:6 1 TCP 2105458943 2620:101:80fc:224:8dd:cbf5:24c1:35db 9 typ host tcptype active
a=candidate:7 1 TCP 2105524479 2620:101:80fc:224:219d:9e56:e0e3:9503 9 typ host tcptype active
a=candidate:8 1 TCP 2105393407 10.252.25.57 9 .221.198
a=rtcp-f4
a=candidate:0 1 UDP 2122252543 10.20.24.132 63416 typ host
a=candidate:4 1 TCP 2105524479 10.20.24.132 9 typ host tcptype active
a=candidate:0 2 UDP 2122252542 10.20.24.132 54932 typ host
a=candidate:4 2 TCP 2105524478 10.20.24.132 9 typ host tcptype active
a=candidate:1 1 UDP 1686052863 64.134.220.204 63416 typ srflx raddr 10.20.24.132 rport 63416
a=candidate:1 2 UDP 1686052862 64.134.220.204 54932 typ srflx raddr 10.20.24.132 rport 54932
a=sendrecv
a=e
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=ssrc:462093353 cname:{54ace55b-4950-d04a-a0f0-07f22b0a82a8}
m=video 62026 UDP/TLS/RTP/SAVPF 120 121 126 97
c=IN IP4 64.134.220.204
a=candidate:0 1 UDP 2122252543 10.20.24.132 62026 typ host
a=candpwd:93Lyy3CWKSpg5URW2cNHi+zt
a=ice-ufrag:+DGd
a=mid:sdparta_1
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:126 ccm fir
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=rtcp-fb:126 goog-remb
a=rtcp-mux
a=rtpmap:126 H264/90000
a=setup:active
a=ssrc:3151863948 cname:xuQ/XUzBRVyBhL9u
a=ssrc:3151863948 msid:2dd448fe-f34c-4f24-92d7-c895d692cbe0 4432de0c-036d-46ef-9a57-f7969eaa21a448 mslabel:2dd448fe-f34c-4f24-92d7-c895d692cbe0
a=ssrc:3151863948 label:4432de0c-036d-46ef-9a57-f7969eaa21a4
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
b=AS:30
a=sendrecv
a=fingerprint:sha-256 2D:64:9F:C4:56:EB:FA:2A:BD:F3:99:83:29:F8:22:49:55:1B:6D:8E:C6:BD:A0:2E:B1:EB:8A:B5:71:F4:EC:3A
a=ice-pwd:93Lyy3CWKSpg5URW2cNHi+zt
a=ice-ufrag:+DGd
a=mid:sdparta_2
a=s����������������������������������������������������������fe-f34c-4f24-92d7-c895d692cbe0
m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 0.0.0.0
a=candidate:1150189783 1 udp 2113937151 10.20.24.132 51738 typ host generation 0 ufrag +DGd network-cost 50
a=sendrecv
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=fingerprint:sha-256 2D:64:9F:C4:56:EB:FA:2A:BD:F3:99:83:29:F8:22:49:55:1B:6D:8E:C6:BD:A0:2E:B1:EB:8A:B5:71:F4:EC:3A
a=fmtp:109 maxplaybackrate=0;stereo=0;useinbandfec=1
a=ice-pwd:93Lyy3CWKSpg5URW2cNHi+zt
a=ice-ufrag:+DGd
a=mid:sdparta_0
a=rtcp:60781116962625945IN IP4 0.0.0.0
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=setup:active
a=ssrc:1719255109 cname:xuQ/XUzBRVyBhL9u
a=ssrc:1719255109 msid:2dd448fe-f34c-4f24-92d7-c895d692cbe0 728ef582-b1cb-4074-abc0-b066f5508466
a=ssrc:1719255109 mslabel:2dd448fe-f34c-4f24-92d7-c895d692cbe0
a=ssrc:1719255l910 abel:728ef582-b1cb-4074-abc0-b066f5508466
m=video 9 UDP/TLS/RTP/SAVPF 126
c=IN IP4 0.0.0.0
a=sendrecv
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:1 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=fingerprint:sha-256 2D:64:9F:C4:56:EB:FA:2A:BD:F3:99:83:29:F8:22:49:55:1B:6D:8E:C6:BD:A0:2E:B1:EB:8A:B5:71:F4:EC:3A
a=fmtp:126 profile-level-id=42e01f;level-asymmetrY-allowed=1;packetization-mode=1
a=ice-pwd:93Lyy3CWKSpg5URW2cNHi+zt
a=ice-ufrag:+DGd
a=mid:sdparta_1
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:126 ccm fir
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=rtcp-fb:126 goog-remb
a=rtcp-mux
a=rtpmap:126 H264/90000
a=setup:active
a=ssrc:3151863948 cname:xuQ/XUzBRVyBhL9u
a=ssrc:3151863948 msid:2dd448fe-f34c-4f24-92d7-c895d692cbe0 4432de0c-036d-46ef-9a57-f7969eaa21a4
a=ssrc:3151(63948 mslabel:2dd448fe-f34c-4f24-92d7-c895d692cbe0
a=ssrc:3151863948 label:4432de0c-036d-46ef-9a57-f7969eaa21a4
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
b=AS:30
a=sendrecv
a=fingerprint:sha-256 2D:64:9F:C4:56:EB:FA:2A:BD:F3:99:83:29:F8:22:49:55:1B:6D:8E:C6:BD:A0:2E:B1:EB:8ndex4 sr=8000,mode=any
a=rtp/1
a=rtpmap:1241754aa
a=ice-ufrag:c2cabe Speex/8000/1
a=control:trackID=
a=fmtp:96 profilemap:124 Speex/8000/1
a=control:trackID=
a=fmtp:96 profile-lev�������������������������������������55
a=mid:sdpart�a7f-a29b-0b41-9ee7-50f38b59c2df}
a=rtcp:57451 IN IP4 63.245.221.198
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=ssrc:1648141107 cname:{df386eca-8c30-4448-9e97-911468065c6b}
m=video 64677 UDP/TLS/RTP/SAVPF 120 121 126 97
c=IN IP4
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x10cd187]

goroutine 1 [running]:
github.com/pions/sdp.(*Address).String(0x0, 0xc0000104d0, 0x1)
	/var/folders/f2/q9n7pkjs47j91q2hjrmzddhc0000gn/T/go-fuzz-build226374785/gopath/src/github.com/pions/sdp/common_description.go:46 +0x37
github.com/pions/sdp.(*ConnectionInformation).String(0xc0000948a0, 0xc000142600)
	/var/folders/f2/q9n7pkjs47j91q2hjrmzddhc0000gn/T/go-fuzz-build226374785/gopath/src/github.com/pions/sdp/common_description.go:32 +0x5e
github.com/pions/sdp.(*SessionDescription).Marshal(0xc00009c120, 0xc0000c4000, 0x1267)
	/var/folders/f2/q9n7pkjs47j91q2hjrmzddhc0000gn/T/go-fuzz-build226374785/gopath/src/github.com/pions/sdp/marshal.go:101 +0xbf3
github.com/pions/sdp.Fuzz(0x4210000, 0x1267, 0x200000, 0x10f6f00)
	/var/folders/f2/q9n7pkjs47j91q2hjrmzddhc0000gn/T/go-fuzz-build226374785/gopath/src/github.com/pions/sdp/fuzz.go:23 +0xab
go-fuzz-dep.Main(0x1118fc8)
	/var/folders/f2/q9n7pkjs47j91q2hjrmzddhc0000gn/T/go-fuzz-build226374785/goroot/src/go-fuzz-dep/main.go:49 +0xad
main.main()
	/var/folders/f2/q9n7pkjs47j91q2hjrmzddhc0000gn/T/go-fuzz-build226374785/gopath/src/github.com/pions/sdp/go.fuzz.main/main.go:10 +0x2d
exit status 2
```

**Comment by trivigy** [comment]
@maxhawkins sorry I am just checking this. Is this a priority for you?

**Comment by maxhawkins** [comment]
It's not effecting me personally but it's a security issue. It should be a priority. Users could send a bad SDP and DDOS the server.

**Comment by josharian** [comment]
I just came across this, and I agree that it should get fixed. I can't reproduce, though, including using the git commit at the time that this was filed. I presume I'm doing it wrong, but I don't see how. @maxhawkins it has been a long time, but do you see what I'm missing for a successful reproduction?

```go
package sdp

import (
	"strings"
	"testing"
)

const (
	Issue13 = `v=0
	o=1 4 0 IN IP4 0
	s=
	t=0 0
	a=
	m=audio 6 UDP/TLS/RTP/AVP 197
	c=IN IP4 63.245.221.198
	a=candidate:0 1 UDP 2122187007 2620:101:80fc:224:8dd:cbf5:24c1:35db 52629 typ host
	a=candidate:2 1 UDP 2122252543 2620:101:80fc:224:219d:9e56:e0e3:9503 52630 typ host
	a=candidate:4 1 UDP 2122121471 10.252.25.57 53802 typ host
	a=candidate:6 1 TCP 2105458943 2620:101:80fc:224:8dd:cbf5:24c1:35db 9 typ host tcptype active
	a=candidate:7 1 TCP 2105524479 2620:101:80fc:224:219d:9e56:e0e3:9503 9 typ host tcptype active
	a=candidate:8 1 TCP 2105393407 10.252.25.57 9 .221.198
	a=rtcp-f4
	a=candidate:0 1 UDP 2122252543 10.20.24.132 63416 typ host
	a=candidate:4 1 TCP 2105524479 10.20.24.132 9 typ host tcptype active
	a=candidate:0 2 UDP 2122252542 10.20.24.132 54932 typ host
	a=candidate:4 2 TCP 2105524478 10.20.24.132 9 typ host tcptype active
	a=candidate:1 1 UDP 1686052863 64.134.220.204 63416 typ srflx raddr 10.20.24.132 rport 63416
	a=candidate:1 2 UDP 1686052862 64.134.220.204 54932 typ srflx raddr 10.20.24.132 rport 54932
	a=sendrecv
	a=e
	a=rtpmap:109 opus/48000/2
	a=rtpmap:9 G722/8000/1
	a=rtpmap:0 PCMU/8000
	a=rtpmap:8 PCMA/8000
	a=rtpmap:101 telephone-event/8000
	a=setup:actpass
	a=ssrc:462093353 cname:{54ace55b-4950-d04a-a0f0-07f22b0a82a8}
	m=video 62026 UDP/TLS/RTP/SAVPF 120 121 126 97
	c=IN IP4 64.134.220.204
	a=candidate:0 1 UDP 2122252543 10.20.24.132 62026 typ host
	a=candpwd:93Lyy3CWKSpg5URW2cNHi+zt
	a=ice-ufrag:+DGd
	a=mid:sdparta_1
	a=rtcp:9 IN IP4 0.0.0.0
	a=rtcp-fb:126 ccm fir
	a=rtcp-fb:126 nack
	a=rtcp-fb:126 nack pli
	a=rtcp-fb:126 goog-remb
	a=rtcp-mux
	a=rtpmap:126 H264/90000
	a=setup:active
	a=ssrc:3151863948 cname:xuQ/XUzBRVyBhL9u
	a=ssrc:3151863948 msid:2dd448fe-f34c-4f24-92d7-c895d692cbe0 4432de0c-036d-46ef-9a57-f7969eaa21a448 mslabel:2dd448fe-f34c-4f24-92d7-c895d692cbe0
	a=ssrc:3151863948 label:4432de0c-036d-46ef-9a57-f7969eaa21a4
	m=application 9 DTLS/SCTP 5000
	c=IN IP4 0.0.0.0
	b=AS:30
	a=sendrecv
	a=fingerprint:sha-256 2D:64:9F:C4:56:EB:FA:2A:BD:F3:99:83:29:F8:22:49:55:1B:6D:8E:C6:BD:A0:2E:B1:EB:8A:B5:71:F4:EC:3A
	a=ice-pwd:93Lyy3CWKSpg5URW2cNHi+zt
	a=ice-ufrag:+DGd
	a=mid:sdparta_2
	a=s����������������������������������������������������������fe-f34c-4f24-92d7-c895d692cbe0
	m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101
	c=IN IP4 0.0.0.0
	a=candidate:1150189783 1 udp 2113937151 10.20.24.132 51738 typ host generation 0 ufrag +DGd network-cost 50
	a=sendrecv
	a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
	a=fingerprint:sha-256 2D:64:9F:C4:56:EB:FA:2A:BD:F3:99:83:29:F8:22:49:55:1B:6D:8E:C6:BD:A0:2E:B1:EB:8A:B5:71:F4:EC:3A
	a=fmtp:109 maxplaybackrate=0;stereo=0;useinbandfec=1
	a=ice-pwd:93Lyy3CWKSpg5URW2cNHi+zt
	a=ice-ufrag:+DGd
	a=mid:sdparta_0
	a=rtcp:60781116962625945IN IP4 0.0.0.0
	a=rtcp-mux
	a=rtpmap:109 opus/48000/2
	a=rtpmap:9 G722/8000/1
	a=rtpmap:0 PCMU/8000
	a=rtpmap:8 PCMA/8000
	a=rtpmap:101 telephone-event/8000
	a=setup:active
	a=ssrc:1719255109 cname:xuQ/XUzBRVyBhL9u
	a=ssrc:1719255109 msid:2dd448fe-f34c-4f24-92d7-c895d692cbe0 728ef582-b1cb-4074-abc0-b066f5508466
	a=ssrc:1719255109 mslabel:2dd448fe-f34c-4f24-92d7-c895d692cbe0
	a=ssrc:1719255l910 abel:728ef582-b1cb-4074-abc0-b066f5508466
	m=video 9 UDP/TLS/RTP/SAVPF 126
	c=IN IP4 0.0.0.0
	a=sendrecv
	a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
	a=extmap:1 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
	a=fingerprint:sha-256 2D:64:9F:C4:56:EB:FA:2A:BD:F3:99:83:29:F8:22:49:55:1B:6D:8E:C6:BD:A0:2E:B1:EB:8A:B5:71:F4:EC:3A
	a=fmtp:126 profile-level-id=42e01f;level-asymmetrY-allowed=1;packetization-mode=1
	a=ice-pwd:93Lyy3CWKSpg5URW2cNHi+zt
	a=ice-ufrag:+DGd
	a=mid:sdparta_1
	a=rtcp:9 IN IP4 0.0.0.0
	a=rtcp-fb:126 ccm fir
	a=rtcp-fb:126 nack
	a=rtcp-fb:126 nack pli
	a=rtcp-fb:126 goog-remb
	a=rtcp-mux
	a=rtpmap:126 H264/90000
	a=setup:active
	a=ssrc:3151863948 cname:xuQ/XUzBRVyBhL9u
	a=ssrc:3151863948 msid:2dd448fe-f34c-4f24-92d7-c895d692cbe0 4432de0c-036d-46ef-9a57-f7969eaa21a4
	a=ssrc:3151(63948 mslabel:2dd448fe-f34c-4f24-92d7-c895d692cbe0
	a=ssrc:3151863948 label:4432de0c-036d-46ef-9a57-f7969eaa21a4
	m=application 9 DTLS/SCTP 5000
	c=IN IP4 0.0.0.0
	b=AS:30
	a=sendrecv
	a=fingerprint:sha-256 2D:64:9F:C4:56:EB:FA:2A:BD:F3:99:83:29:F8:22:49:55:1B:6D:8E:C6:BD:A0:2E:B1:EB:8ndex4 sr=8000,mode=any
	a=rtp/1
	a=rtpmap:1241754aa
	a=ice-ufrag:c2cabe Speex/8000/1
	a=control:trackID=
	a=fmtp:96 profilemap:�124 Speex/8000/1
	a=control:trackID=
	a=fmtp:96 profile-lev�������������������������������������55
	a=mid:sdpart�a7f-a29b-0b41-9ee7-50f38b59c2df}
	a=rtcp:57451 IN IP4 63.245.221.198
	a=rtcp-mux
	a=rtpmap:109 opus/48000/2
	a=rtpmap:9 G722/8000/1
	a=rtpmap:0 PCMU/8000
	a=rtpmap:8 PCMA/8000
	a=rtpmap:101 telephone-event/8000
	a=setup:actpass
	a=ssrc:1648141107 cname:{df386eca-8c30-4448-9e97-911468065c6b}
	m=video 64677 UDP/TLS/RTP/SAVPF 120 121 126 97
	c=IN IP4`
)

// constToWire converts a conveniently written Go string
// to a wire-format SDP byte slice by trimming
// all per-line leading and trailing spaces and converting \n to \r\n.
func constToWire(s string) []byte {
	lines := strings.Split(s, "\n")
	var b []byte
	for _, line := range lines {
		b = append(b, strings.TrimSpace(line)...)
		b = append(b, '\r', '\n')
	}
	return b
}

func TestIssue13(t *testing.T) {
	var sd SessionDescription
	sd.Unmarshal(constToWire(Issue13)) // panics?
}
```

**Comment by josharian** [comment]
Also, do you still have your fuzz function and supporting code floating around anywhere? Thanks!

**Comment by maxhawkins** [comment]
It's possible the encoding got off when I posted to GitHub. I believe I found this with a fuzzer so you might be able to get a similar result by running a fuzzer on the parser.

**Comment by josharian** [comment]
@maxhawkins ack. I'm going to close this issue, then, and run a fuzzer locally for a while to attempt to reproduce. Thanks.

**Comment by josharian** [comment]
Ah--the issue description says unmarshalling, but the stack trace shows this occurs during marshalling. I have reproduced and minimized and have a fix locally.
